steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/prospeccaob2b-489003/dados_cnpj_image:latest', '.']
images:
- 'gcr.io/prospeccaob2b-489003/dados_cnpj_image:latest'
options:
  defaultLogsBucketBehavior: CLOUD_LOGGING_ONLY
